<?php

namespace Database\Seeders;

use App\Models\Lawyer;
use Illuminate\Database\Seeder;

class LawyerSeeder extends Seeder
{
    public function run(): void
    {
        $lawyers = [
            [
                'first_name' => 'Sarah',
                'last_name' => 'Mthembu',
                'email' => 'sarah.mthembu@legalaidsa.co.za',
                'phone' => '+27 11 234 5678',
                'mobile' => '+27 82 345 6789',
                'license_number' => 'LSA-JHB-2015-001',
                'firm_name' => 'Mthembu & Associates',
                'bio' => 'Sarah is a dedicated human rights lawyer with over 8 years of experience in family law and criminal defense. She is passionate about providing accessible legal services to all South Africans.',
                'specializations' => ['Family Law', 'Criminal Law', 'Human Rights'],
                'languages' => ['English', 'Zulu', 'Sotho'],
                'years_experience' => 8,
                'address' => '123 Commissioner Street',
                'city' => 'Johannesburg',
                'province' => 'Gauteng',
                'postal_code' => '2001',
                'latitude' => -26.2041,
                'longitude' => 28.0473,
                'admission_date' => '2015-03-15',
                'courts_admitted' => ['Magistrates Court', 'High Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call', 'Phone call'],
                'consultation_fee' => 850.00,
                'website' => 'https://www.mthembulaw.co.za',
                'business_hours' => [
                    'Monday' => '08:00 - 17:00',
                    'Tuesday' => '08:00 - 17:00',
                    'Wednesday' => '08:00 - 17:00',
                    'Thursday' => '08:00 - 17:00',
                    'Friday' => '08:00 - 16:00',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.7,
                'review_count' => 23,
            ],
            [
                'first_name' => 'David',
                'last_name' => 'van der Merwe',
                'email' => 'david@vdmlaw.co.za',
                'phone' => '+27 21 456 7890',
                'mobile' => '+27 83 456 7890',
                'license_number' => 'LSA-CPT-2012-045',
                'firm_name' => 'Van der Merwe Legal Consultants',
                'bio' => 'David specializes in commercial law and property transactions with over 12 years of experience. He has successfully handled numerous high-profile property deals across the Western Cape.',
                'specializations' => ['Property Law', 'Commercial Law', 'Banking Law'],
                'languages' => ['English', 'Afrikaans'],
                'years_experience' => 12,
                'address' => '456 Adderley Street',
                'city' => 'Cape Town',
                'province' => 'Western Cape',
                'postal_code' => '8001',
                'latitude' => -33.9249,
                'longitude' => 18.4241,
                'admission_date' => '2012-07-20',
                'courts_admitted' => ['Magistrates Court', 'High Court', 'Supreme Court of Appeal'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call'],
                'consultation_fee' => 1200.00,
                'website' => 'https://www.vdmlaw.co.za',
                'business_hours' => [
                    'Monday' => '09:00 - 17:30',
                    'Tuesday' => '09:00 - 17:30',
                    'Wednesday' => '09:00 - 17:30',
                    'Thursday' => '09:00 - 17:30',
                    'Friday' => '09:00 - 16:00',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.5,
                'review_count' => 18,
            ],
            [
                'first_name' => 'Nomsa',
                'last_name' => 'Khumalo',
                'email' => 'nomsa@khumalolaw.co.za',
                'phone' => '+27 31 789 0123',
                'mobile' => '+27 84 567 8901',
                'license_number' => 'LSA-DBN-2018-089',
                'firm_name' => 'Khumalo Employment Law Specialists',
                'bio' => 'Nomsa is a specialist employment lawyer focusing on workplace discrimination, unfair dismissals, and labour relations. She has represented numerous clients at the CCMA and Labour Court.',
                'specializations' => ['Employment Law', 'Labour Relations', 'Human Rights'],
                'languages' => ['English', 'Zulu', 'Xhosa'],
                'years_experience' => 6,
                'address' => '789 Smith Street',
                'city' => 'Durban',
                'province' => 'KwaZulu-Natal',
                'postal_code' => '4001',
                'latitude' => -29.8587,
                'longitude' => 31.0218,
                'admission_date' => '2018-01-10',
                'courts_admitted' => ['Magistrates Court', 'Labour Court', 'Labour Appeal Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call', 'Phone call', 'Email consultation'],
                'consultation_fee' => 750.00,
                'website' => 'https://www.khumalolaw.co.za',
                'business_hours' => [
                    'Monday' => '08:30 - 17:00',
                    'Tuesday' => '08:30 - 17:00',
                    'Wednesday' => '08:30 - 17:00',
                    'Thursday' => '08:30 - 17:00',
                    'Friday' => '08:30 - 16:30',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.8,
                'review_count' => 31,
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Oosthuizen',
                'email' => 'michael@oosthuizenlaw.co.za',
                'phone' => '+27 51 234 5678',
                'mobile' => '+27 85 678 9012',
                'license_number' => 'LSA-BFN-2010-023',
                'firm_name' => 'Oosthuizen Criminal Defense',
                'bio' => 'Michael is a seasoned criminal defense attorney with 14 years of experience. He has successfully defended clients in high-profile criminal cases and specializes in white-collar crime.',
                'specializations' => ['Criminal Law', 'Constitutional Law', 'Administrative Law'],
                'languages' => ['English', 'Afrikaans', 'Sotho'],
                'years_experience' => 14,
                'address' => '321 President Brand Street',
                'city' => 'Bloemfontein',
                'province' => 'Free State',
                'postal_code' => '9300',
                'latitude' => -29.0852,
                'longitude' => 26.1596,
                'admission_date' => '2010-05-12',
                'courts_admitted' => ['Magistrates Court', 'High Court', 'Supreme Court of Appeal'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call'],
                'consultation_fee' => 950.00,
                'website' => 'https://www.oosthuizenlaw.co.za',
                'business_hours' => [
                    'Monday' => '08:00 - 17:00',
                    'Tuesday' => '08:00 - 17:00',
                    'Wednesday' => '08:00 - 17:00',
                    'Thursday' => '08:00 - 17:00',
                    'Friday' => '08:00 - 15:30',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.6,
                'review_count' => 27,
            ],
            [
                'first_name' => 'Priya',
                'last_name' => 'Patel',
                'email' => 'priya@patelconsumer.co.za',
                'phone' => '+27 11 987 6543',
                'mobile' => '+27 86 789 0123',
                'license_number' => 'LSA-JHB-2017-067',
                'firm_name' => 'Patel Consumer Rights Law',
                'bio' => 'Priya specializes in consumer protection law and debt counseling. She has helped hundreds of clients resolve disputes with banks, retailers, and service providers.',
                'specializations' => ['Consumer Rights', 'Debt & Credit', 'Banking Law'],
                'languages' => ['English', 'Hindi', 'Gujarati'],
                'years_experience' => 7,
                'address' => '654 Pritchard Street',
                'city' => 'Johannesburg',
                'province' => 'Gauteng',
                'postal_code' => '2001',
                'latitude' => -26.1951,
                'longitude' => 28.0480,
                'admission_date' => '2017-09-03',
                'courts_admitted' => ['Magistrates Court', 'High Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call', 'Phone call'],
                'consultation_fee' => 650.00,
                'website' => 'https://www.patelconsumer.co.za',
                'business_hours' => [
                    'Monday' => '09:00 - 17:00',
                    'Tuesday' => '09:00 - 17:00',
                    'Wednesday' => '09:00 - 17:00',
                    'Thursday' => '09:00 - 17:00',
                    'Friday' => '09:00 - 16:00',
                    'Saturday' => '09:00 - 13:00',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.9,
                'review_count' => 42,
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Makhubela',
                'email' => 'james@makhubelalaw.co.za',
                'phone' => '+27 15 456 7890',
                'mobile' => '+27 87 890 1234',
                'license_number' => 'LSA-LIM-2019-012',
                'firm_name' => 'Makhubela Legal Services',
                'bio' => 'James is a young but dedicated lawyer who focuses on family law and personal injury cases. He is committed to serving rural communities in Limpopo province.',
                'specializations' => ['Family Law', 'Personal Injury', 'Property Law'],
                'languages' => ['English', 'Pedi', 'Venda', 'Tsonga'],
                'years_experience' => 5,
                'address' => '147 Grobler Street',
                'city' => 'Polokwane',
                'province' => 'Limpopo',
                'postal_code' => '0700',
                'latitude' => -23.9045,
                'longitude' => 29.4688,
                'admission_date' => '2019-11-15',
                'courts_admitted' => ['Magistrates Court', 'High Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Phone call'],
                'consultation_fee' => 550.00,
                'business_hours' => [
                    'Monday' => '08:00 - 17:00',
                    'Tuesday' => '08:00 - 17:00',
                    'Wednesday' => '08:00 - 17:00',
                    'Thursday' => '08:00 - 17:00',
                    'Friday' => '08:00 - 16:00',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.3,
                'review_count' => 15,
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Botha',
                'email' => 'lisa@bothalaw.co.za',
                'phone' => '+27 18 345 6789',
                'mobile' => '+27 88 901 2345',
                'license_number' => 'LSA-NW-2013-034',
                'firm_name' => 'Botha Mining Law Specialists',
                'bio' => 'Lisa specializes in mining law, environmental law, and commercial litigation. She has extensive experience in the mining industry and regulatory compliance.',
                'specializations' => ['Environmental Law', 'Commercial Law', 'Administrative Law'],
                'languages' => ['English', 'Afrikaans', 'Tswana'],
                'years_experience' => 11,
                'address' => '258 Beyers Naude Drive',
                'city' => 'Rustenburg',
                'province' => 'North West',
                'postal_code' => '0300',
                'latitude' => -25.6672,
                'longitude' => 27.2424,
                'admission_date' => '2013-04-08',
                'courts_admitted' => ['Magistrates Court', 'High Court', 'Land Claims Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call'],
                'consultation_fee' => 1100.00,
                'website' => 'https://www.bothalaw.co.za',
                'business_hours' => [
                    'Monday' => '08:30 - 17:30',
                    'Tuesday' => '08:30 - 17:30',
                    'Wednesday' => '08:30 - 17:30',
                    'Thursday' => '08:30 - 17:30',
                    'Friday' => '08:30 - 16:30',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.4,
                'review_count' => 19,
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'email' => 'ahmed@hassanlaw.co.za',
                'phone' => '+27 11 567 8901',
                'mobile' => '+27 89 012 3456',
                'license_number' => 'LSA-JHB-2016-078',
                'firm_name' => 'Hassan Immigration Law',
                'bio' => 'Ahmed specializes in immigration law and has helped numerous individuals and families navigate the complex South African immigration system.',
                'specializations' => ['Immigration Law', 'Human Rights', 'Administrative Law'],
                'languages' => ['English', 'Arabic', 'Urdu'],
                'years_experience' => 8,
                'address' => '369 Fox Street',
                'city' => 'Johannesburg',
                'province' => 'Gauteng',
                'postal_code' => '2001',
                'latitude' => -26.2023,
                'longitude' => 28.0436,
                'admission_date' => '2016-02-28',
                'courts_admitted' => ['Magistrates Court', 'High Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call', 'Phone call'],
                'consultation_fee' => 800.00,
                'website' => 'https://www.hassanlaw.co.za',
                'business_hours' => [
                    'Monday' => '09:00 - 18:00',
                    'Tuesday' => '09:00 - 18:00',
                    'Wednesday' => '09:00 - 18:00',
                    'Thursday' => '09:00 - 18:00',
                    'Friday' => '09:00 - 17:00',
                ],
                'is_verified' => true,
                'is_active' => true,
                'verified_at' => now(),
                'verified_by' => 'System Admin',
                'rating' => 4.6,
                'review_count' => 24,
            ],
            [
                'first_name' => 'Catherine',
                'last_name' => 'Williams',
                'email' => 'catherine@williamslaw.co.za',
                'phone' => '+27 41 678 9012',
                'mobile' => '+27 72 123 4567',
                'license_number' => 'LSA-PE-2014-056',
                'firm_name' => 'Williams Medical Malpractice Law',
                'bio' => 'Catherine specializes in medical malpractice and personal injury law. She has successfully represented clients in complex medical negligence cases.',
                'specializations' => ['Medical Malpractice', 'Personal Injury', 'Insurance Law'],
                'languages' => ['English', 'Afrikaans', 'Xhosa'],
                'years_experience' => 10,
                'address' => '741 Main Street',
                'city' => 'Port Elizabeth',
                'province' => 'Eastern Cape',
                'postal_code' => '6001',
                'latitude' => -33.9580,
                'longitude' => 25.6176,
                'admission_date' => '2014-06-30',
                'courts_admitted' => ['Magistrates Court', 'High Court'],
                'accepts_new_clients' => true,
                'consultation_methods' => ['In-person', 'Video call'],
                'consultation_fee' => 1000.00,
                'website' => 'https://www.williamslaw.co.za',
                'business_hours' => [
                    'Monday' => '08:00 - 17:00',
                    'Tuesday' => '08:00 - 17:00',
                    'Wednesday' => '08:00 - 17:00',
                    'Thursday' => '08:00 - 17:00',
                    'Friday' => '08:00 - 16:00',
                ],
                'is_verified' => false,
                'is_active' => true,
                'rating' => 4.2,
                'review_count' => 13,
            ],
        ];

        foreach ($lawyers as $lawyerData) {
            Lawyer::firstOrCreate(
                ['email' => $lawyerData['email']],
                $lawyerData
            );
        }
    }
}